---
- name: Include vars
  ansible.builtin.include_vars:
    file: '{{ experience.path }}'

- name: Extract information
  set_fact:
    __experience_bucket: '{{ experience.path.split("/")[3] }}'
    __experience_name: '{{ experience.path.split("/")[6] }}'

- name: Execute automation controller resource configuration
  ansible.builtin.include_role:
    name: infra.controller_configuration.dispatch
  vars:
    controller_configuration_async_delay: 1
    controller_configuration_async_retries: 30
